project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: 1
files:
  - source: /module/webui/locales/strings/en.xml
    translation: /module/webui/locales/strings/%locale%.xml
